### PR TITLE
Push v1.2.2 relay-webapp to PRD

### PR DESCRIPTION
**Pull request by CarlosPintos**

### CODE REVIEW

**Comment by andresmoschini** [comment]
Wow! are we upgrading mseditor in Relay? is it working fine? (Take into account that we have some special behaviors in Relay's editor)

**Comment by CarlosPintos** [comment]
@andresmoschini, According to @juanasas  it is a stable version of MSEditor. I don't know the differences between v1.0.0-build588 v and version v1.0.1-build169. @juanasas  Could you help us to know the risks of changing?

**Comment by juanasas** [comment]
> @andresmoschini, According to @juanasas it is a stable version of MSEditor. I don't know the differences between v1.0.0-build588 and version v1.0.1-build169. @juanasas Could you help us to know the risks of changing?

Actually, I don't know what the special relay behaviors are.

**Comment by andresmoschini** [comment]
> > @andresmoschini, According to @juanasas it is a stable version of MSEditor. I don't know the differences between v1.0.0-build588 and version v1.0.1-build169. @juanasas Could you help us to know the risks of changing?
> 
> Actually, I don't know what the special relay behaviors are.

For example, Relay does not have social networks, products, etc. 

Maybe you can check the history and differences with Doppler in the `adapterService.js` and, of course, test it manually a lot hehe.

**Comment by CarlosPintos** [comment]
@andresmoschini  it sounds re-check from our side. Please @juanasas  help me to re-check it

**Comment by CarlosPintos** [comment]
@andresmoschini . We've checked it with @juanasas  and We saw that fileServerImagesURL setting is only needed to keep working fine in relay-webapp.

**Pull request merged**
